### ISSUE TITLE
Übercharge on spawn never runs out if you don't move

### ISSUE THREAD

**Issue by woisalreadytaken** [ScrewdriverHyena/tfgungame-redux#1]
Players can stand still and be übercharged forever. You can also move while keeping the übercharge if you use a taunt that forces movement, like the Conga.

**Comment by Serafeline** [comment]
not a bug, see tfgg_spawnprotect_length. ask the server operator to change this value.

**Comment by Serafeline** [comment]
correction: being able to move with a taunt that forces movement will be fixed
